"""initial

Revision ID: 5f161593b9f2
Revises: 
Create Date: 2026-03-23 15:53:42.825725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f161593b9f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=10), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('programa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['programa_id'], ['programa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_usuario')
    )
    op.create_table('aspirante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=20), nullable=True),
    sa.Column('numero_documento', sa.String(length=20), nullable=True),
    sa.Column('nombres', sa.String(length=100), nullable=True),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('tipo_aspirante', sa.String(length=50), nullable=True),
    sa.Column('programa_id', sa.Integer(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('lugar_nacimiento', sa.String(length=100), nullable=True),
    sa.Column('direccion_residencia', sa.String(length=200), nullable=True),
    sa.Column('estrato', sa.Integer(), nullable=True),
    sa.Column('foto_archivo', sa.String(length=255), nullable=True),
    sa.Column('documento_id_archivo', sa.String(length=255), nullable=True),
    sa.Column('diploma_archivo', sa.String(length=255), nullable=True),
    sa.Column('motivacion', sa.Text(), nullable=True),
    sa.Column('medio_enterado', sa.String(length=100), nullable=True),
    sa.Column('canal_informativo', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['programa_id'], ['programa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_documento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aspirante')
    op.drop_table('usuario')
    op.drop_table('programa')
    # ### end Alembic commands ###
